package dev.xqedii.ultimateUI.gui.model;

import org.bukkit.entity.TextDisplay.TextAlignment;
import org.bukkit.util.Vector;

public class HoverElement {
   public String id;
   public String type;
   public String targetId;
   public String targetKind;
   public String targetPath;
   public String componentName;
   public String bindingX;
   public String bindingY;
   public String bindingWidth;
   public String bindingHeight;
   public double centerX;
   public double centerY;
   public double z;
   public double runtimeZ;
   public double width;
   public double height;
   public double rotationDeg;
   public double pivotOffsetX;
   public double pivotOffsetY;
   public boolean mirrorX;
   public boolean mirrorY;
   public boolean itemDisplay;
   public boolean itemDisplayBlock;
   public boolean visible = true;
   public int opacity;
   public String text;
   public String hoverText;
   public double outlineSize;
   public String outlineColor;
   public String outlineText;
   public String onClickAction;
   public String onLeftClickAction;
   public String onRightClickAction;
   public String clickEffect;
   public boolean interactive;
   public Vector baseLocation;
   public Vector baseScale;
   public String roundedCornerUnicode;
   public String roundedCornerUnicodeTopLeft;
   public String roundedCornerUnicodeTopRight;
   public String roundedCornerUnicodeBottomRight;
   public String roundedCornerUnicodeBottomLeft;
   public double roundedTopLeftOffsetX;
   public double roundedTopLeftOffsetY;
   public double roundedTopRightOffsetX;
   public double roundedTopRightOffsetY;
   public double roundedBottomRightOffsetX;
   public double roundedBottomRightOffsetY;
   public double roundedBottomLeftOffsetX;
   public double roundedBottomLeftOffsetY;
   public TextAlignment hudAlignment = TextAlignment.CENTER;
   public TextAlignment textAlignment = TextAlignment.CENTER;
   public double hitboxOffsetX;
   public double hitboxOffsetY;
   public boolean disableHitbox;
}
