# Downloaded from spilledspigot.com | user_id: 128 | username: LapHa | hash: eb88e288ab7ea351c84bcf27 | token: EB88E288
#Loading screen:
screen.loading=000000
screen.loading.bar=211613
screen.loading.progress=ffffff
screen.loading.outline=ffffff
screen.loading.blend=off
# Downloaded from spilledspigot.com | user_id: 128 | username: LapHa | hash: eb88e288ab7ea351c84bcf27 | token: EB88E288
