package dev.xqedii.ultimateUI.service.gui.model;

import dev.xqedii.ultimateUI.gui.model.HoverElement;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.util.Vector;

public final class EditorSession {
   public String pageName;
   public File pageFile;
   public YamlConfiguration yaml;
   public List<Map<String, Object>> rawBlocks = new ArrayList<>();
   public List<Map<String, Object>> renderBlocks = new ArrayList<>();
   public Map<String, YamlConfiguration> components = new HashMap<>();
   public List<Map<String, Object>> shellBlocks = new ArrayList<>();
   public final Map<String, EditorRect> shellRuntimeRects = new HashMap<>();
   public final Map<String, ConfigurationSection> shellSectionCache = new LinkedHashMap<>();
   public final Map<String, Map<String, Object>> shellBlockMapCache = new LinkedHashMap<>();
   public final Map<String, EditorRect> shellStaticRectCache = new HashMap<>();
   public boolean shellCacheBuilt;
   public final List<HoverElement> elements = new ArrayList<>();
   public final Map<String, Vector> handleCenters = new HashMap<>();
   public final Map<String, EditorRect> resizeStartBounds = new LinkedHashMap<>();
   public final Map<String, EditorRect> resizeInheritedRootStartBoundsByPath = new LinkedHashMap<>();
   public final Map<String, Object> resizeInheritedChildrenSnapshotByPath = new LinkedHashMap<>();
   public PreviewViewport previewViewport;
   public double previewDefaultZoom = 1.0;
   public boolean previewMode;
   public boolean editMode;
   public boolean hudTextOnlyMode;
   public double runtimeHudSneakVisualOffsetY;
   public boolean runtimeAutoCloseAfterAnimations;
   public boolean runtimeAnimationLoop;
   public String pageOpenEffect = "";
   public String pageCloseEffect = "";
   public boolean pageCloseUseHud;
   public boolean pendingCloseEffect;
   public String activeEffectOverride;
   public long runtimeOpenAnimationToken;
   public double runtimeHitboxOffsetX;
   public double runtimeHitboxOffsetY;
   public double pageOpenSpawnOffsetX;
   public double pageOpenSpawnOffsetY;
   public final Map<String, Boolean> runtimePageKeepOpen = new LinkedHashMap<>();
   public final Map<String, Boolean> runtimePageReopen = new LinkedHashMap<>();
   public final Map<String, Boolean> runtimePageCloseOnDeath = new LinkedHashMap<>();
   public final Map<String, Boolean> runtimePageCloseOnDamage = new LinkedHashMap<>();
   public String runtimeAnimationScopePageKey;
   public final LinkedHashMap<String, Long> runtimeOpenAnimationTokensByPage = new LinkedHashMap<>();
   public EditorTool activeTool = EditorTool.CURSOR;
   public String hoveredElementId;
   public String selectedElementId;
   public final LinkedHashSet<String> additionalSelectedElementIds = new LinkedHashSet<>();
   public String activeHandle;
   public double cursorX;
   public double cursorY;
   public String cursorColor = "ffffff";
   public String cursorDefaultUnicode = "\ue67c";
   public String cursorHoverUnicode = "\ue67d";
   public String cursorDragUnicode = "\ue67e";
   public String cursorSliderDragUnicode = "\ue67f";
   public String cursorResizeTrBlUnicode = "\ue680";
   public String cursorResizeTlBrUnicode = "\ue681";
   public String cursorResizeVerticalUnicode = "\ue682";
   public String cursorResizeHorizontalUnicode = "\ue683";
   public String cursorRuntimeUnicode = "\ue67c";
   public double lastCursorVisualHitX = Double.NaN;
   public double lastCursorVisualHitY = Double.NaN;
   public int lastCursorVisualStateHash;
   public String lastCursorVisualDesiredUnicode;
   public double lastProcessedHitX = Double.NaN;
   public double lastProcessedHitY = Double.NaN;
   public long lastLeftClickTick;
   public String hoveredHandle;
   public double hitboxOffsetX;
   public double hitboxOffsetY;
   public boolean lastShiftHeld;
   public boolean resizeAnchorValid;
   public double resizeSelectionStartX;
   public double resizeSelectionStartY;
   public double resizeSelectionStartW;
   public double resizeSelectionStartH;
   public double resizeStartCursorX;
   public double resizeStartCursorY;
   public double resizeLastCursorX;
   public double resizeLastCursorY;
   public boolean resizeStepReady;
   public long lastScaleToggleTick = -2305843009213693952L;
   public boolean handlesCollapsed;
   public boolean moveDragActive;
   public boolean previewPanActive;
   public boolean selectionOutlineVisible = true;
   public boolean marqueeSelectActive;
   public double marqueeStartCursorX;
   public double marqueeStartCursorY;
   public boolean alignToolbarVisible;
   public String alignToolbarHoverActionId;
   public EditorRect alignToolbarBounds;
   public final LinkedHashMap<String, EditorRect> alignToolbarActionRects = new LinkedHashMap<>();
   public long alignToolbarClickGuardUntilTick = -2305843009213693952L;
   public boolean alignToolbarConsumeHoldClick;
   public long pasteSelectionClickGuardUntilTick = -2305843009213693952L;
   public double dragStartCursorX;
   public double dragStartCursorY;
   public final Map<String, EditorRect> moveStartBounds = new LinkedHashMap<>();
   public String moveDragStartSnapshot;
   public boolean moveDragMutated;
   public double previewPanStartCursorX;
   public double previewPanStartCursorY;
   public double previewPanStartX;
   public double previewPanStartY;
   public String resizeDragStartSnapshot;
   public boolean resizeDragMutated;
   public EditorPropertyField pendingPropertyField;
   public String pendingItemDesignInventoryTargetId;
   public String pendingActionTargetId;
   public int pendingActionIndex = -1;
   public EditorSavePopupField pendingSavePopupField;
   public String pendingTextToolTargetId;
   public String pendingTextToolOriginalText;
   public boolean pendingTextToolPlaceholderActive;
   public boolean savePopupVisible;
   public boolean preferencesPopupVisible;
   public boolean welcomePopupVisible;
   public boolean welcomePopupAcknowledged;
   public List<Map<String, Object>> menuTemplateBlocks = new ArrayList<>();
   public boolean menuFilePopupVisible;
   public boolean menuFilePopupEditAction = true;
   public boolean menuFilePopupImageMode;
   public String menuFilePopupSelectedPage;
   public int menuFilePopupScrollOffset;
   public boolean menuFilePopupScrollbarDragActive;
   public double menuFilePopupScrollbarDragOffsetY;
   public int menuFilePopupScrollbarY;
   public int menuFilePopupTransitionTicksOverride = -1;
   public final List<String> menuFilePopupPageKeys = new ArrayList<>();
   public final LinkedHashMap<String, String> menuFilePopupNames = new LinkedHashMap<>();
   public final LinkedHashMap<String, String> menuFilePopupDescriptions = new LinkedHashMap<>();
   public final LinkedHashMap<String, String> menuFilePopupCommands = new LinkedHashMap<>();
   public String savePopupName;
   public String savePopupDescription;
   public String savePopupCommand;
   public boolean displayHotbar;
   public boolean displayHand;
   public boolean optimizedEditor;
   public boolean editorSounds = true;
   public boolean opacitySliderDragActive;
   public Integer opacitySliderLastValue;
   public boolean animationTimelineSliderDragActive;
   public Double animationTimelineSliderDragTick;
   public int animationTimelineTick;
   public Double animationTimelineSliderStartX;
   public boolean animationTimelinePanelVisible;
   public boolean animationTimelineComponentVisible;
   public String animationTimelineTargetId;
   public String animationTimelineRenderedSignature;
   public String animationTimelineSelectedTargetId;
   public String animationTimelineSelectedRow;
   public int animationTimelineSelectedTick = -1;
   public final LinkedHashSet<Integer> animationTimelineAdditionalSelectedTicks = new LinkedHashSet<>();
   public final LinkedHashSet<String> animationTimelineAdditionalSelectedKeyframeRefs = new LinkedHashSet<>();
   public String animationTimelineContextTargetId;
   public String animationTimelineContextRow;
   public int animationTimelineContextTick = -1;
   public String animationTimelineKeyframeClipboardRow;
   public Object animationTimelineKeyframeClipboardValue;
   public int animationTimelineKeyframeClipboardAnchorTick = -1;
   public String animationTimelineKeyframeClipboardAnchorRef;
   public final LinkedHashMap<Integer, Object> animationTimelineKeyframeClipboardValuesByTick = new LinkedHashMap<>();
   public final LinkedHashMap<String, Object> animationTimelineKeyframeClipboardValuesByRef = new LinkedHashMap<>();
   public boolean animationTimelineKeyframeDragActive;
   public int animationTimelineKeyframeDragRuntimeTick = -1;
   public final LinkedHashMap<Integer, Integer> animationTimelineKeyframeDragRuntimeTickByLogicalTick = new LinkedHashMap<>();
   public final LinkedHashMap<String, Integer> animationTimelineKeyframeDragRuntimeTickByRef = new LinkedHashMap<>();
   public String animationTimelineKeyframeDragStartSnapshot;
   public boolean animationTimelineKeyframeDragMutated;
   public double animationTimelineKeyframeDragStartHitX = Double.NaN;
   public double animationTimelineKeyframeDragHitOffsetX;
   public String animationPreviewTargetId;
   public double animationPreviewOffsetX;
   public double animationPreviewOffsetY;
   public EditorRect animationPreviewBaseBounds;
   public EditorRect animationPreviewAppliedBounds;
   public Double animationPreviewBaseRotation;
   public Double animationPreviewAppliedRotation;
   public Integer animationPreviewBaseOpacity;
   public Integer animationPreviewAppliedOpacity;
   public final LinkedHashMap<String, EditorRect> animationPreviewAdditionalBaseBoundsByTarget = new LinkedHashMap<>();
   public final LinkedHashMap<String, EditorRect> animationPreviewAdditionalAppliedBoundsByTarget = new LinkedHashMap<>();
   public final LinkedHashMap<String, Double> animationPreviewAdditionalBaseRotationByTarget = new LinkedHashMap<>();
   public final LinkedHashMap<String, Double> animationPreviewAdditionalAppliedRotationByTarget = new LinkedHashMap<>();
   public final LinkedHashMap<String, Integer> animationPreviewAdditionalBaseOpacityByTarget = new LinkedHashMap<>();
   public final LinkedHashMap<String, Integer> animationPreviewAdditionalAppliedOpacityByTarget = new LinkedHashMap<>();
   public String animationTimelineImplicitBaseTargetId;
   public EditorRect animationTimelineImplicitBaseBounds;
   public final LinkedHashMap<String, EditorRect> animationTimelineImplicitBaseBoundsByTarget = new LinkedHashMap<>();
   public final LinkedHashSet<String> runtimeAnimationTimelineKeyframeIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> runtimeAnimationPreviewPathIds = new LinkedHashSet<>();
   public boolean sidebarFieldDragActive;
   public EditorPropertyField sidebarFieldDragField;
   public double sidebarFieldDragStartCursorX;
   public double sidebarFieldDragStartValue;
   public Double sidebarFieldDragLastValue;
   public String sidebarFieldDragStartSnapshot;
   public boolean sidebarFieldDragMutated;
   public boolean sidebarOpacityRefreshTriggered;
   public String opacitySliderDragStartSnapshot;
   public boolean opacitySliderDragMutated;
   public EditorSidebarTab rightSidebarTab = EditorSidebarTab.LAYERS;
   public EditorSidebarTab rightSidebarHoverTab;
   public final LinkedHashMap<String, Boolean> sidebarPanelVisibilityStates = new LinkedHashMap<>();
   public int rightSidebarIndicatorAnimationToken;
   public int rightSidebarPanelTransitionToken;
   public boolean fileDropdownVisible;
   public boolean fileNavbarVisualActive;
   public String fileDropdownHoverTargetId;
   public boolean editDropdownVisible;
   public boolean editNavbarVisualActive;
   public String editDropdownHoverTargetId;
   public boolean selectionDropdownVisible;
   public boolean selectionNavbarVisualActive;
   public String selectionDropdownHoverTargetId;
   public boolean layerDropdownVisible;
   public boolean layerNavbarVisualActive;
   public String layerDropdownHoverTargetId;
   public boolean windowDropdownVisible;
   public String windowDropdownHoverTargetId;
   public boolean windowNavbarVisualActive;
   public boolean keyframeDropdownVisible;
   public String keyframeDropdownHoverTargetId;
   public boolean keyframeTimelineDropdownVisible;
   public String keyframeTimelineDropdownHoverTargetId;
   public boolean cursorPageDropdownVisible;
   public String cursorPageDropdownHoverTargetId;
   public int cursorPageDropdownOpenToken;
   public boolean cursorLayersDropdownVisible;
   public String cursorLayersDropdownHoverTargetId;
   public String cursorLayersDropdownContextTargetId;
   public String cursorLayersDropdownContextTargetPath;
   public int cursorLayersDropdownOpenToken;
   public int pivotDebugMarkerToken;
   public boolean cursorActionsDropdownVisible;
   public String cursorActionsDropdownHoverTargetId;
   public boolean cursorActionsEditDropdownVisible;
   public String cursorActionsEditDropdownHoverTargetId;
   public int cursorLayersDropdownResolvedShellIdentity;
   public int cursorLayersDropdownResolvedShellSize = -1;
   public String cursorLayersDropdownResolvedPanelPath;
   public final LinkedHashMap<String, String> cursorLayersDropdownRuntimeIdsByBase = new LinkedHashMap<>();
   public final List<String> cursorLayersDropdownResolvedItemIds = new ArrayList<>();
   public final List<String> cursorLayersDropdownResolvedDynamicItemIds = new ArrayList<>();
   public final List<String> cursorLayersDropdownResolvedPanelMemberIds = new ArrayList<>();
   public final LinkedHashMap<String, Boolean> cursorLayersDropdownActionVisibilityStates = new LinkedHashMap<>();
   public final LinkedHashMap<String, Boolean> cursorLayersDropdownItemActiveStates = new LinkedHashMap<>();
   public String cursorLayersDropdownLastActionId;
   public long cursorLayersDropdownLastActionTick = -2305843009213693952L;
   public boolean previewSizeToastVisible;
   public boolean previewSizeToastPendingReveal;
   public int previewSizeToastToken;
   public int shellOpacityBatchDepth;
   public final LinkedHashMap<String, Integer> pendingShellOpacity = new LinkedHashMap<>();
   public int layersScrollOffset;
   public double layersScrollPosition;
   public double layersScrollTarget;
   public double layersScrollVelocity;
   public int layersScrollAnimationToken;
   public int layersScrollTopFlashToken;
   public int layersScrollBottomFlashToken;
   public int layersRenderedStart = -1;
   public int layersRenderedCount;
   public double layersRenderedFraction;
   public long layersRenderedSignature;
   public boolean layersRenderQueued;
   public int actionsScrollOffset;
   public int actionsScrollTopFlashToken;
   public int actionsScrollBottomFlashToken;
   public int actionsSelectedIndex = -1;
   public int actionsReorderArmedIndex = -1;
   public int actionsReorderCurrentIndex = -1;
   public boolean actionsReorderActive;
   public double actionsReorderStartHitX;
   public double actionsReorderStartHitY;
   public boolean actionsReorderHistoryRecorded;
   public int actionsLastClickIndex = -1;
   public long actionsLastClickTick = -2305843009213693952L;
   public final List<Integer> actionsRenderedRawIndexes = new ArrayList<>();
   public final LinkedHashSet<String> runtimeActionShellIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> runtimeActionReorderGhostShellIds = new LinkedHashSet<>();
   public boolean runtimeActionChainLocked;
   public long runtimeActionChainToken;
   public boolean runtimeActionAwaitingLeftRelease;
   public String layersReorderArmedTargetId;
   public double layersReorderArmedStartHitX;
   public double layersReorderArmedStartHitY;
   public String layersReorderTargetId;
   public String layersReorderHoverTargetId;
   public String layersReorderGhostLabel;
   public boolean layersReorderActive;
   public int layersReorderPreviewInsertIndex = -1;
   public double layersReorderLastHitX = Double.NaN;
   public double layersReorderLastHitY = Double.NaN;
   public int layersReorderAutoScrollDirection;
   public int layersReorderAutoScrollToken;
   public int layersReorderReleaseWatchToken;
   public final LinkedHashSet<String> runtimeLayerReorderGhostShellIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> collapsedLayerTargetIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> runtimeLayerShellIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> hiddenLayerTargetIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> lockedLayerTargetIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> spawnOpacityRetoggledTargetIds = new LinkedHashSet<>();
   public final LinkedHashSet<String> pendingSpawnOpacityRetoggleTargetIds = new LinkedHashSet<>();
   public boolean spawnOpacityRetoggleTaskQueued;
   public boolean suppressHudTransitionDuringStructureDeletion;
   public final Map<String, List<String>> pageUndoSnapshots = new LinkedHashMap<>();
   public final Map<String, List<String>> pageRedoSnapshots = new LinkedHashMap<>();
   public boolean historyApplying;
   public List<Map<String, Object>> editClipboardBlocks = new ArrayList<>();
   public Map<String, Object> actionsClipboardAction;
   public List<Map<String, Object>> editorShellTemplateBlocks = new ArrayList<>();
   public final List<String> openEditorPages = new ArrayList<>();
   public int activePagesScrollOffset;
   public String activePagesArmedPageKey;
   public double activePagesArmedStartHitX;
   public double activePagesArmedStartHitY;
   public boolean activePagesReorderActive;
   public String activePagesReorderPageKey;
   public int activePagesReorderInsertIndex = -1;
   public int activePagesReorderReleaseWatchToken;
   public int activePagesVisibleHoveredSlot = -1;
   public final LinkedHashMap<Integer, String> activePagesRenderedSlotStates = new LinkedHashMap<>();
   public String editorColor1 = "66b9ff";
   public String editorColor2 = "ffffff";
   public boolean colorPickerVisible;
   public int colorPickerSlot = 1;
   public boolean colorPickerGradDragActive;
   public boolean colorPickerHueDragActive;
   public boolean colorPickerHexInputPending;
   public double colorPickerGradAbsX;
   public double colorPickerGradAbsY;
   public double colorPickerHueAbsY;
}
